package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Company implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Address")
   private java.lang.String address;
   @org.kie.api.definition.type.Label(value = "Program Type")
   private org.epa.mda.poc.ProgramType programType;

   public Company()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public org.epa.mda.poc.ProgramType getProgramType()
   {
      return this.programType;
   }

   public void setProgramType(org.epa.mda.poc.ProgramType programType)
   {
      this.programType = programType;
   }

   public Company(java.lang.String name, java.lang.String address,
         org.epa.mda.poc.ProgramType programType)
   {
      this.name = name;
      this.address = address;
      this.programType = programType;
   }

}