package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Company implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Address")
   @org.kie.api.definition.type.Description("to be looked up")
   private java.lang.String address;
   @org.kie.api.definition.type.Label("Part 79")
   private java.lang.Boolean part79;

   @org.kie.api.definition.type.Label("Part 80")
   private java.lang.Boolean part80;

   @org.kie.api.definition.type.Label("Program Type 1")
   private java.lang.String programType1;

   @org.kie.api.definition.type.Label("Business Activity 1")
   @org.kie.api.definition.type.Description("informs part regulation string list")
   private java.lang.String busActivity1;

   @org.kie.api.definition.type.Label("Business Activity 2")
   @org.kie.api.definition.type.Description("informs part regulation strings list")
   private java.lang.String busActivity2;

   @org.kie.api.definition.type.Label("Program Type 2")
   private java.lang.String programType2;

   @org.kie.api.definition.type.Label("City")
   @org.kie.api.definition.type.Description("to be looked up")
   private java.lang.String city;

   @org.kie.api.definition.type.Label("County")
   @org.kie.api.definition.type.Description("to be looked up")
   private java.lang.String county;

   @org.kie.api.definition.type.Label("State")
   @org.kie.api.definition.type.Description("to be looked up")
   private java.lang.String state;

   @org.kie.api.definition.type.Label("Register As Facility")
   private java.lang.Boolean registerAsFacility;

   @org.kie.api.definition.type.Label("ID")
   @org.kie.api.definition.type.Description("to be looked up")
   private java.lang.String id;

   @org.kie.api.definition.type.Label("Supplemental Location")
   private java.lang.String supplementalLocation;

   @org.kie.api.definition.type.Label("Zip Code")
   private java.lang.String zip;

   @org.kie.api.definition.type.Label("FIPS Code")
   private java.lang.String fipsCode;

   @org.kie.api.definition.type.Label("Latitude")
   private java.lang.String latitude;

   @org.kie.api.definition.type.Label("Longitude")
   private java.lang.String longitude;

   @org.kie.api.definition.type.Label(value = "Part 80 Regulations")
   private java.util.List<java.lang.String> part80Regs;

   @org.kie.api.definition.type.Label(value = "Part 79 Regulations")
   private java.util.List<java.lang.String> part79Regs;

   public Company()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.Boolean getPart79()
   {
      return this.part79;
   }

   public void setPart79(java.lang.Boolean part79)
   {
      this.part79 = part79;
   }

   public java.lang.Boolean getPart80()
   {
      return this.part80;
   }

   public void setPart80(java.lang.Boolean part80)
   {
      this.part80 = part80;
   }

   public java.lang.String getBusActivity1()
   {
      return this.busActivity1;
   }

   public void setBusActivity1(java.lang.String busActivity1)
   {
      this.busActivity1 = busActivity1;
   }

   public java.lang.String getBusActivity2()
   {
      return this.busActivity2;
   }

   public void setBusActivity2(java.lang.String busActivity2)
   {
      this.busActivity2 = busActivity2;
   }

   public java.lang.String getProgramType1()
   {
      return this.programType1;
   }

   public void setProgramType1(java.lang.String programType1)
   {
      this.programType1 = programType1;
   }

   public java.lang.String getProgramType2()
   {
      return this.programType2;
   }

   public void setProgramType2(java.lang.String programType2)
   {
      this.programType2 = programType2;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.String county)
   {
      this.county = county;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.Boolean getRegisterAsFacility()
   {
      return this.registerAsFacility;
   }

   public void setRegisterAsFacility(java.lang.Boolean registerAsFacility)
   {
      this.registerAsFacility = registerAsFacility;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getSupplementalLocation()
   {
      return this.supplementalLocation;
   }

   public void setSupplementalLocation(java.lang.String supplementalLocation)
   {
      this.supplementalLocation = supplementalLocation;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public java.lang.String getFipsCode()
   {
      return this.fipsCode;
   }

   public void setFipsCode(java.lang.String fipsCode)
   {
      this.fipsCode = fipsCode;
   }

   public java.lang.String getLatitude()
   {
      return this.latitude;
   }

   public void setLatitude(java.lang.String latitude)
   {
      this.latitude = latitude;
   }

   public java.lang.String getLongitude()
   {
      return this.longitude;
   }

   public void setLongitude(java.lang.String longitude)
   {
      this.longitude = longitude;
   }

   public java.util.List<java.lang.String> getPart80Regs()
   {
      return this.part80Regs;
   }

   public void setPart80Regs(java.util.List<java.lang.String> part80Regs)
   {
      this.part80Regs = part80Regs;
   }
   
   public void addPart80Regs(java.lang.String value) {
	   this.part80Regs.add(value);
   }

   public java.util.List<java.lang.String> getPart79Regs()
   {
      return this.part79Regs;
   }

   public void setPart79Regs(java.util.List<java.lang.String> part79Regs)
   {
      this.part79Regs = part79Regs;
   }
   
   public void addPart79Regs(java.lang.String value) {
	   this.part79Regs.add(value);
   }

   public Company(java.lang.String name, java.lang.String address,
         java.lang.Boolean part79, java.lang.Boolean part80,
         java.lang.String programType1, java.lang.String busActivity1,
         java.lang.String busActivity2, java.lang.String programType2,
         java.lang.String city, java.lang.String county, java.lang.String state,
         java.lang.Boolean registerAsFacility, java.lang.String id,
         java.lang.String supplementalLocation, java.lang.String zip,
         java.lang.String fipsCode, java.lang.String latitude,
         java.lang.String longitude,
         java.util.List<java.lang.String> part80Regs,
         java.util.List<java.lang.String> part79Regs)
   {
      this.name = name;
      this.address = address;
      this.part79 = part79;
      this.part80 = part80;
      this.programType1 = programType1;
      this.busActivity1 = busActivity1;
      this.busActivity2 = busActivity2;
      this.programType2 = programType2;
      this.city = city;
      this.county = county;
      this.state = state;
      this.registerAsFacility = registerAsFacility;
      this.id = id;
      this.supplementalLocation = supplementalLocation;
      this.zip = zip;
      this.fipsCode = fipsCode;
      this.latitude = latitude;
      this.longitude = longitude;
      this.part80Regs = part80Regs;
      this.part79Regs = part79Regs;
   }

}