package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Element implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Percent Markup")
   private java.lang.Integer percentMarkup;

   public Element()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getPercentMarkup()
   {
      return this.percentMarkup;
   }

   public void setPercentMarkup(java.lang.Integer percentMarkup)
   {
      this.percentMarkup = percentMarkup;
   }

   public Element(java.lang.String name, java.lang.Integer percentMarkup)
   {
      this.name = name;
      this.percentMarkup = percentMarkup;
   }

}