package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Element implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Element() {
    }

}