package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Facility implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Address")
   private java.lang.String address;

   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.String id;

   @org.kie.api.definition.type.Label(value = "City")
   private java.lang.String city;

   @org.kie.api.definition.type.Label(value = "County")
   private java.lang.String county;

   @org.kie.api.definition.type.Label(value = "State")
   private java.lang.String state;

   public Facility()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.String county)
   {
      this.county = county;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public Facility(java.lang.String name, java.lang.String address,
         java.lang.String id, java.lang.String city, java.lang.String county,
         java.lang.String state)
   {
      this.name = name;
      this.address = address;
      this.id = id;
      this.city = city;
      this.county = county;
      this.state = state;
   }

}