package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Facility implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Company Name")
   private java.lang.String companyName;
   @org.kie.api.definition.type.Label(value = "Company Address")
   private java.lang.String companyAddress;

   public Facility()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getCompanyName()
   {
      return this.companyName;
   }

   public void setCompanyName(java.lang.String companyName)
   {
      this.companyName = companyName;
   }

   public java.lang.String getCompanyAddress()
   {
      return this.companyAddress;
   }

   public void setCompanyAddress(java.lang.String companyAddress)
   {
      this.companyAddress = companyAddress;
   }

   public Facility(java.lang.String name, java.lang.String companyName,
         java.lang.String companyAddress)
   {
      this.name = name;
      this.companyName = companyName;
      this.companyAddress = companyAddress;
   }

}