package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Facility implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Address")
   private java.lang.String address;

   @org.kie.api.definition.type.Label("ID")
   private java.lang.String id;

   @org.kie.api.definition.type.Label("City")
   private java.lang.String city;

   @org.kie.api.definition.type.Label("County")
   private java.lang.String county;

   @org.kie.api.definition.type.Label("State")
   private java.lang.String state;

   @org.kie.api.definition.type.Label(value = "Zip Code")
   private java.lang.String zip;

   @org.kie.api.definition.type.Label(value = "FIPS Code")
   private java.lang.String fips;

   @org.kie.api.definition.type.Label(value = "Latitude")
   private java.lang.String latitude;

   @org.kie.api.definition.type.Label(value = "Longitude")
   private java.lang.String longitude;

   public Facility()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCounty()
   {
      return this.county;
   }

   public void setCounty(java.lang.String county)
   {
      this.county = county;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public java.lang.String getFips()
   {
      return this.fips;
   }

   public void setFips(java.lang.String fips)
   {
      this.fips = fips;
   }

   public java.lang.String getLatitude()
   {
      return this.latitude;
   }

   public void setLatitude(java.lang.String latitude)
   {
      this.latitude = latitude;
   }

   public java.lang.String getLongitude()
   {
      return this.longitude;
   }

   public void setLongitude(java.lang.String longitude)
   {
      this.longitude = longitude;
   }

   public Facility(java.lang.String name, java.lang.String address,
         java.lang.String id, java.lang.String city, java.lang.String county,
         java.lang.String state, java.lang.String zip, java.lang.String fips,
         java.lang.String latitude, java.lang.String longitude)
   {
      this.name = name;
      this.address = address;
      this.id = id;
      this.city = city;
      this.county = county;
      this.state = state;
      this.zip = zip;
      this.fips = fips;
      this.latitude = latitude;
      this.longitude = longitude;
   }

}