package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductReportMeta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Associated Product")
   private java.lang.String associatedProduct;
   @org.kie.api.definition.type.Label(value = "Date")
   private java.lang.String date;
   @org.kie.api.definition.type.Label(value = "Signer")
   private java.lang.String signer;
   @org.kie.api.definition.type.Label(value = "Phone Number")
   private java.lang.String phoneNumber;
   @org.kie.api.definition.type.Label(value = "Contact")
   private java.lang.String contact;

   public ProductReportMeta()
   {
   }

   public java.lang.String getAssociatedProduct()
   {
      return this.associatedProduct;
   }

   public void setAssociatedProduct(java.lang.String associatedProduct)
   {
      this.associatedProduct = associatedProduct;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   public void setDate(java.lang.String date)
   {
      this.date = date;
   }

   public java.lang.String getSigner()
   {
      return this.signer;
   }

   public void setSigner(java.lang.String signer)
   {
      this.signer = signer;
   }

   public java.lang.String getPhoneNumber()
   {
      return this.phoneNumber;
   }

   public void setPhoneNumber(java.lang.String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public java.lang.String getContact()
   {
      return this.contact;
   }

   public void setContact(java.lang.String contact)
   {
      this.contact = contact;
   }

   public ProductReportMeta(java.lang.String associatedProduct,
         java.lang.String date, java.lang.String signer,
         java.lang.String phoneNumber, java.lang.String contact)
   {
      this.associatedProduct = associatedProduct;
      this.date = date;
      this.signer = signer;
      this.phoneNumber = phoneNumber;
      this.contact = contact;
   }

}