package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductReportMeta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Associated Product")
   private java.lang.String associatedProduct;

   @org.kie.api.definition.type.Label("Date")
   private java.util.Date date;

   @org.kie.api.definition.type.Label("Signer")
   private java.lang.String signer;

   @org.kie.api.definition.type.Label("Phone Number")
   private java.lang.String phoneNumber;

   @org.kie.api.definition.type.Label("Contact")
   private java.lang.String contact;

   @org.kie.api.definition.type.Label(value = "Reporting Year")
   private java.lang.String reportingYear;

   public ProductReportMeta()
   {
   }

   public java.lang.String getAssociatedProduct()
   {
      return this.associatedProduct;
   }

   public void setAssociatedProduct(java.lang.String associatedProduct)
   {
      this.associatedProduct = associatedProduct;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.String getSigner()
   {
      return this.signer;
   }

   public void setSigner(java.lang.String signer)
   {
      this.signer = signer;
   }

   public java.lang.String getPhoneNumber()
   {
      return this.phoneNumber;
   }

   public void setPhoneNumber(java.lang.String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public java.lang.String getContact()
   {
      return this.contact;
   }

   public void setContact(java.lang.String contact)
   {
      this.contact = contact;
   }

   public java.lang.String getReportingYear()
   {
      return this.reportingYear;
   }

   public void setReportingYear(java.lang.String reportingYear)
   {
      this.reportingYear = reportingYear;
   }

   public ProductReportMeta(java.lang.String associatedProduct,
         java.util.Date date, java.lang.String signer,
         java.lang.String phoneNumber, java.lang.String contact,
         java.lang.String reportingYear)
   {
      this.associatedProduct = associatedProduct;
      this.date = date;
      this.signer = signer;
      this.phoneNumber = phoneNumber;
      this.contact = contact;
      this.reportingYear = reportingYear;
   }

}