package org.epa.mda.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProgramType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Type")
   private java.lang.String type;

   @org.kie.api.definition.type.Label(value = "Business Activity 1")
   private java.lang.String businessActivity1;

   @org.kie.api.definition.type.Label(value = "Business Activity 2")
   private java.lang.String businessActivity2;

   public ProgramType()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getBusinessActivity1()
   {
      return this.businessActivity1;
   }

   public void setBusinessActivity1(java.lang.String businessActivity1)
   {
      this.businessActivity1 = businessActivity1;
   }

   public java.lang.String getBusinessActivity2()
   {
      return this.businessActivity2;
   }

   public void setBusinessActivity2(java.lang.String businessActivity2)
   {
      this.businessActivity2 = businessActivity2;
   }

   public ProgramType(java.lang.String type, java.lang.String businessActivity1,
         java.lang.String businessActivity2)
   {
      this.type = type;
      this.businessActivity1 = businessActivity1;
      this.businessActivity2 = businessActivity2;
   }

}